// Code generated by goctl. DO NOT EDIT.
package types

type FeedHandlerRequest struct {
	LastestTime int64  `json:"LastestTime"`
	Token       string `json:"Token"`
}

type FeedHandlerResponse struct {
	StatusCode int32  `json:"StatusCode""`
	StatusMsg  string `json:"StatusMsg"`
	VideoList  Video  `json:"VideoList"`
	NextTime   int64  `json:""NextTime"`
}

type Video struct {
	Id      int64  `json:"Id"`
	Author  User   `json:"Author"`
	PlayUrl string `json:"PlayUrl"`
}

type User struct {
	Id   int64  `json:"Id"`
	Name string `json:"Name"`
}

type UserRegisterHandlerRequest struct {
	UserName string `json:"UserName"`
	PassWord string `json:"PassWord"`
}

type UserRegisterHandlerResponse struct {
	StatusCode int32  `json:"StatusCode"`
	StatusMsg  string `json:"StatusMsg"`
	UserID     int64  `json:"UserID"`
	Token      string `json:"token"`
}
